feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 120
work_dir: ./work_dir_VAC/debug/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 5
device: 0
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
#load_weights: /hdd1/zy/code/GCN_cue1/work_dir_concat/debug/dev_39.00_epoch45_model.pt

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: stream_VAC.SLRModel
#model: slr_network.GCN
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18 #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf
  conv_type: 2
  use_bn: 1
  # SMKD
#  share_classifier: True
#  weight_norm: True


#  nfeat: 512
#  dropout: 0.5
#  nhid: 1024
#  hidden_size1: 512
